name: NoHungerLoss
api: 3.0.0
version: 1.0.0
author: Angel
main: Angel\NoHungerLoss\Main
commands:
   hunger:
      description: Set positions for no hunger zone!
      default: false

permissions:
   hunger.cmd:
      description: Access hunger command to select positions!
